return {
  "stevearc/conform.nvim",
  optional = true,
  opts = {
    formatters_by_ft = {
      -- ["javascript"] = { "custom_prettier" },
      -- ["javascriptreact"] = { "custom_prettier" },
      -- ["typescript"] = { "custom_prettier" },
      -- ["typescriptreact"] = { "custom_prettier" },
      -- ["vue"] = { "custom_prettier" },
      ["javascriptreact"] = { "prettier" },
      ["typescript"] = { "prettier" },
      ["typescriptreact"] = { "prettier" },
      ["vue"] = { "prettier" },
      ["javascript"] = { "prettier" },
      ["css"] = { "prettier" },
      ["scss"] = { "prettier" },
      ["less"] = { "prettier" },
      ["html"] = { "prettier" },
      ["json"] = { "prettier" },
      ["jsonc"] = { "prettier" },
      ["yaml"] = { "prettier" },
      ["markdown"] = { "prettier" },
      ["markdown.mdx"] = { "prettier" },
      ["graphql"] = { "prettier" },
      ["handlebars"] = { "prettier" },
      ["java"] = { "google-java-format" },
      ["go"] = { "gofmpt", "goimports" },
      ["rust"] = { "rustfmt" },
    },
    formatters = {
      custom_prettier = {
        command = "prettier",
        args = { "--no-semi", "--single-quote", "$FILENAME" },
      },
    },
  },
}
